import type { Metadata } from "next";
import "./globals.scss";
import LenisProvider from "./common/LenisProvider";
import Nav from "./common/Nav";

export const metadata: Metadata = {
  title: "React Practice Components | Healoz",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <LenisProvider>
          <Nav />
          {children}
        </LenisProvider>
      </body>
    </html>
  );
}
